matrix:
  include:
    - sudo: required
      services:
        - docker
    - os: osx

env:
  global:
    - TWINE_USERNAME=joerick
      # Note: TWINE_PASSWORD is set in Travis settings

script:
  - pip install cibuildwheel==0.2.0
  - cibuildwheel --output-dir wheelhouse

deploy:
  provider: script
  script:
    - pip install twine
    - twine upload wheelhouse/*.whl
  skip_cleanup: true
  on:
    tags: true
