matrix:
  include:
    - sudo: required
      services:
        - docker
    - os: osx

env:
  global:
    - TWINE_USERNAME=joerick
      # Note: TWINE_PASSWORD is set in Travis settings

script:
  - pip install cibuildwheel==0.2.0
  - cibuildwheel --output-dir wheelhouse
  - |
    set -o errexit
    if [[ $TRAVIS_TAG ]]; then
      pip install twine
      twine upload wheelhouse/*.whl
    else
      echo "Skipping wheel upload to PyPI because this is not a tag build"
    fi
